## MythicAI RPG-Story Plugin

name: Roleplay Story
creators:
  - Igor Alexey
description: >
  RPG-Story project type for MythicAI.

license: GPL-3.0
repository: https://github.com/vortexdevsoftware/RPG-Story

# Come contribute! ;-)